/**
 * Task Mongoose Schema
 *
 * This is the database model for the Task entity. Key Zorbit patterns demonstrated:
 *
 *   1. SHORT HASH IDENTIFIERS — Every entity gets a hashId like TSK-A2F3.
 *      These are immutable, globally unique (best-effort), and non-sequential.
 *      They are used in URLs and API responses instead of MongoDB _id.
 *
 *   2. NAMESPACE ISOLATION — organizationHashId ensures data is scoped to
 *      the organization. Every query MUST filter by organizationHashId.
 *
 *   3. PII MARKERS — Fields that contain PII (assigneeName, assigneeEmail)
 *      are stored as PII vault tokens, not raw values. The raw PII lives
 *      only in the PII Vault service. Our database stores tokens like PII-92AF.
 *
 *   4. TIMESTAMPS — Mongoose's { timestamps: true } auto-manages createdAt/updatedAt.
 */
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type TaskDocument = Task & Document;

@Schema({ collection: 'tasks', timestamps: true })
export class Task {
  /**
   * Short hash identifier (e.g. TSK-A2F3).
   * Generated by HashIdService. Used in URLs and API responses.
   * NEVER use MongoDB's _id externally.
   */
  @Prop({ required: true, unique: true, index: true })
  hashId!: string;

  /**
   * Organization scope — enforces namespace isolation.
   * Every query MUST include this field to prevent cross-org data leaks.
   */
  @Prop({ required: true, index: true })
  organizationHashId!: string;

  /** Task title — plain text, not PII */
  @Prop({ required: true })
  title!: string;

  /** Task description — rich text content, not PII */
  @Prop({ default: '' })
  description!: string;

  /**
   * Task status — follows a defined workflow:
   *   todo -> in_progress -> review -> done
   *
   * Status transitions are enforced in the service layer, not the schema.
   * This allows the business rules to evolve independently of the data model.
   */
  @Prop({
    required: true,
    default: 'todo',
    enum: ['todo', 'in_progress', 'review', 'done'],
    index: true,
  })
  status!: string;

  /**
   * Priority level — used for sorting and filtering in the task list.
   */
  @Prop({
    required: true,
    default: 'medium',
    enum: ['low', 'medium', 'high', 'critical'],
    index: true,
  })
  priority!: string;

  /**
   * PII TOKEN — Assignee display name.
   * This stores a PII vault token (e.g. PII-92AF), NOT the raw name.
   * To display the actual name, call PII Vault's /detokenize endpoint.
   */
  @Prop({ default: null })
  assigneeNameToken!: string | null;

  /**
   * PII TOKEN — Assignee email address.
   * This stores a PII vault token (e.g. PII-81F3), NOT the raw email.
   */
  @Prop({ default: null })
  assigneeEmailToken!: string | null;

  /**
   * Assignee user hash ID (e.g. U-81F3).
   * This is NOT PII — it's a platform identifier used for lookups and filtering.
   */
  @Prop({ default: null, index: true })
  assigneeHashId!: string | null;

  /** Due date for the task. Null means no deadline. */
  @Prop({ default: null })
  dueDate!: Date | null;

  /** Tags for categorization and filtering */
  @Prop({ type: [String], default: [] })
  tags!: string[];

  /** User hash ID of the task creator */
  @Prop({ required: true })
  createdByHashId!: string;

  // createdAt and updatedAt are auto-managed by Mongoose timestamps: true
}

export const TaskSchema = SchemaFactory.createForClass(Task);

// Compound index for the most common query: list tasks in an org, sorted by date
TaskSchema.index({ organizationHashId: 1, createdAt: -1 });

// Index for filtering by status within an org
TaskSchema.index({ organizationHashId: 1, status: 1 });

// Index for filtering by assignee within an org
TaskSchema.index({ organizationHashId: 1, assigneeHashId: 1 });
